# Configuration file for py-load-pmda
#
# This file contains settings for the database connection and for each
# dataset to be processed. Settings can be overridden by environment variables.

database:
  # The type of database adapter to use. 'postgres' is the default.
  type: "postgres"

  # Connection details for the target database.
  # These can be overridden by env vars like PMDA_DB_HOST, PMDA_DB_USER, etc.
  host: "localhost"
  port: 5432
  user: "admin"
  password: "password"
  dbname: "pmda_db"

datasets:
  approvals:
    # Class names for the ETL components for this dataset
    extractor: "ApprovalsExtractor"
    parser: "ApprovalsParser"
    transformer: "ApprovalsTransformer"

    # Target table and schema in the database
    table_name: "pmda_approvals"
    schema_name: "public"

    # Load strategy configuration
    load_mode: "overwrite" # or "append", "merge"
    primary_key: ["approval_id"] # for merge mode

  jader:
    extractor: "JaderExtractor"
    parser: "JaderParser"
    transformer: "JaderTransformer"
    table_name: "pmda_jader"
    schema_name: "public"
    load_mode: "append"

  package_inserts:
    extractor: "PackageInsertsExtractor"
    parser: "PackageInsertsParser"
    transformer: "PackageInsertsTransformer"
    table_name: "pmda_package_inserts"
    schema_name: "public"
    load_mode: "merge"
    primary_key: ["document_id"]
    columns:
      document_id: "VARCHAR(64)"
      raw_data_full: "JSONB"
      _meta_source_url: "TEXT"
      _meta_extraction_ts_utc: "TIMESTAMPTZ"
      _meta_load_ts_utc: "TIMESTAMPTZ"
      _meta_pipeline_version: "VARCHAR(50)"
      _meta_source_content_hash: "VARCHAR(64)"
