name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.2
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Check if lock file is up to date
      working-directory: ./py-load-pmda
      run: poetry lock --check

    - name: Install dependencies
      working-directory: ./py-load-pmda
      run: poetry install --no-interaction

    - name: Run tests
      working-directory: ./py-load-pmda
      run: poetry run pytest
